# Generated by Django 3.1.4 on 2021-02-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.cart')),
                ('drink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.drink')),
            ],
        ),
        migrations.CreateModel(
            name='Order_dessert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.cart')),
                ('dessert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.dessert')),
            ],
        ),
    ]
