# Generated by Django 3.1.4 on 2021-02-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_order_dessert_order_drink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
    ]
