# Generated by Django 3.1.4 on 2021-02-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_pizza_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.cart')),
                ('pizza_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.pizza')),
                ('size_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.size')),
            ],
        ),
    ]
